{{- if .Values.featureGates.enableInferenceSetController -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kaito.fullname" . }}-inferenceset-rolebinding
  labels:
   {{- include "kaito.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kaito.fullname" . }}-inferenceset-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ include "kaito.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
{{- end -}}
