apiVersion: v1
kind: ConfigMap
metadata:
  name: kaito-supported-models
  namespace: {{ .Release.Namespace }}
data:
  SupportedModels: |
    models:
      - name: base
        type: text-generation
        runtime: tfs
        tag: 0.0.5
      - name: llama-3.1-8b-instruct
        type: text-generation
        version: https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct/commit/0e9e39f249a16976918f6564b8830bc894c89659
        runtime: tfs
        downloadAtRuntime: true
        tag: 0.2.0
      - name: llama-3.3-70b-instruct
        type: text-generation
        version: https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct/commit/6f6073b423013f6a7d4d9f39144961bfbfbc386b
        runtime: tfs
        downloadAtRuntime: true
        tag: 0.0.1
      - name: deepseek-r1-0528
        type: text-generation
        version: https://huggingface.co/deepseek-ai/DeepSeek-R1-0528/commit/4236a6af538feda4548eca9ab308586007567f52
        runtime: tfs
        downloadAtRuntime: true
        tag: 0.0.1
      - name: deepseek-v3-0324
        type: text-generation
        version: https://huggingface.co/deepseek-ai/DeepSeek-V3-0324/commit/e9b33add76883f293d6bf61f6bd89b497e80e335
        runtime: tfs
        downloadAtRuntime: true
        tag: 0.0.1
      - name: falcon-7b
        type: text-generation
        version: https://huggingface.co/tiiuae/falcon-7b/commit/898df1396f35e447d5fe44e0a3ccaaaa69f30d36
        runtime: tfs
        tag: 0.2.0
      - name: falcon-7b-instruct
        type: text-generation
        version: https://huggingface.co/tiiuae/falcon-7b-instruct/commit/cf4b3c42ce2fdfe24f753f0f0d179202fea59c99
        runtime: tfs
        tag: 0.2.0
      - name: falcon-40b
        type: text-generation
        version: https://huggingface.co/tiiuae/falcon-40b/commit/4a70170c215b36a3cce4b4253f6d0612bb7d4146
        runtime: tfs
        tag: 0.2.0
      - name: falcon-40b-instruct
        type: text-generation
        version: https://huggingface.co/tiiuae/falcon-40b-instruct/commit/ecb78d97ac356d098e79f0db222c9ce7c5d9ee5f
        runtime: tfs
        tag: 0.2.0
      - name: mistral-7b
        type: text-generation
        version: https://huggingface.co/mistralai/Mistral-7B-v0.3/commit/d8cadc02ac76bd617a919d50b092e59d2d110aff
        runtime: tfs
        tag: 0.2.0
      - name: mistral-7b-instruct
        type: text-generation
        version: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3/commit/e0bc86c23ce5aae1db576c8cca6f06f1f73af2db
        runtime: tfs
        tag: 0.2.0
      - name: phi-2
        type: text-generation
        version: https://huggingface.co/microsoft/phi-2/commit/ef382358ec9e382308935a992d908de099b64c23
        runtime: tfs
        tag: 0.2.0
      - name: phi-3-mini-4k-instruct
        type: text-generation
        version: https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/commit/0a67737cc96d2554230f90338b163bc6380a2a85
        runtime: tfs
        tag: 0.2.0
      - name: phi-3-mini-128k-instruct
        type: text-generation
        version: https://huggingface.co/microsoft/Phi-3-mini-128k-instruct/commit/072cb7562cb8c4adf682a8e186aaafa49469eb5d
        runtime: tfs
        tag: 0.2.0
      - name: phi-3-medium-4k-instruct
        type: text-generation
        version: https://huggingface.co/microsoft/Phi-3-medium-4k-instruct/commit/b64223aaea6fbf273c0c8cd0801d5e732dce8897
        runtime: tfs
        tag: 0.2.0
      - name: phi-3-medium-128k-instruct
        type: text-generation
        version: https://huggingface.co/microsoft/Phi-3-medium-128k-instruct/commit/fa7d2aa4f5ea69b2e36b20d050cdae79c9bfbb3f
        runtime: tfs
        tag: 0.2.0
      - name: phi-3.5-mini-instruct
        type: text-generation
        version: https://huggingface.co/microsoft/Phi-3.5-mini-instruct/commit/3145e03a9fd4cdd7cd953c34d9bbf7ad606122ca
        runtime: tfs
        tag: 0.2.0
      - name: phi-4-mini-instruct
        type: text-generation
        version: https://huggingface.co/microsoft/Phi-4-mini-instruct/commit/c0fb9e74abda11b496b7907a9c6c9009a7a0488f
        runtime: tfs
        tag: 0.2.0
      - name: phi-4
        type: text-generation
        version: https://huggingface.co/microsoft/phi-4/commit/187ef0342fff0eb3333be9f00389385e95ef0b61
        runtime: tfs
        tag: 0.2.0
      - name: qwen2.5-coder-7b-instruct
        type: text-generation
        version: https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct/commit/c03e6d358207e414f1eca0bb1891e29f1db0e242
        runtime: tfs
        tag: 0.2.0
      - name: qwen2.5-coder-32b-instruct
        type: text-generation
        version: https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct/commit/381fc969f78efac66bc87ff7ddeadb7e73c218a7
        runtime: tfs
        tag: 0.2.0
      - name: deepseek-r1-distill-qwen-14b
        type: text-generation
        version: https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B/commit/1df8507178afcc1bef68cd8c393f61a886323761
        runtime: tfs
        tag: 0.2.0
      - name: deepseek-r1-distill-llama-8b
        type: text-generation
        version: https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B/commit/6a6f4aa4197940add57724a7707d069478df56b1
        runtime: tfs
        tag: 0.2.0
